
export const ENUM_USER_ROLE = {
    USER: "USER",
    ADMIN: "ADMIN",
    SUPER_ADMIN: "SUPER_ADMIN",
    EXPART: "EXPERT"
}

export const ENUM_SESSION_STATUS= {
   ONGOING: "Ongoing",
   UPCOMING: "Upcoming",
   COMPLETED: "Completed"
}

export const ENUM_NOTIFICATION_TYPE = {
    LIKE_POST : "LIKE_POST",
    COMMENT_POST : "COMMENT_POST",
    SENT_MESSAGE : "SENT_MESSAGE",
    SENT_WAVE : "SENT_WAVE",
    ACCEPT_WAVE : "ACCEPT_WAVE",
    REJECT_WAVE : "REJECT_WAVE",
    OTHER : "OTHER"
}

export const ENUM_PAYOUT_STATUS = {
  NOT_ELIGIBLE : "NOT_ELIGIBLE",
  ELIGIBLE : "ELIGIBLE",
  PAYOUT_PENDING : "PAYOUT_PENDING",
  PAYOUT_PROCESSING : "PAYOUT_PROCESSING",
  PAYOUT_SUCCESS : "PAYOUT_SUCCESS",
  PAYOUT_FAILED : "PAYOUT_FAILED",
  SETTLED : "SETTLED"
}


// export const ENUM_POST_PRIORITY = {
//     URGENT: "Urgent",
//     LATER: "Later"
// }
